### ISSUE TITLE
按照网上的方法编写的py脚本为何不能连接新区（图书馆）校园网

### ISSUE THREAD

**Issue by miles-xi** [HowardZorn/HFUT-DrCOM#2]
同学你好，能否麻烦看下我的代码。

参考： https://zhuanlan.zhihu.com/p/370801224

代码如下：
<img width="920" alt="屏幕截图 2021-09-22 164453" src="https://user-images.githubusercontent.com/41740721/134312136-d781968a-6b7b-47bd-a2f2-2a957ab49b8a.png">

虽然status code返回200，但是网络并没有连接，打开任意网页还是会被重定向到登录页。

**Comment by HowardZorn** [comment]
这个代码很明显url params和header搞不清楚是什么，建议不要使用。另外这个代码我没有参与编写，浪费时间问我其实意义不大，我相信原作者更懂。

**Comment by miles-xi** [comment]
好的，谢谢
